version: '3.8'

services:
  frontend:
    build: ./vocabulary-front
    restart: always
    ports:
      - '5173:5173'
    volumes:
      - /app/node_modules
      - ./vocabulary-front:/app
  backend:
    build: ./vocabulary-api
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - /app/node_modules
      - ./vocabulary-api:/app
  mysql:
    image: mysql
    restart: always
    environment:
#      MYSQL_HOST: mysql
#      MYSQL_USER: root
#      MYSQL_PORT: '3306'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DB: vocabulary_db
    volumes:
      - mysql_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - '8888:8080'
volumes:
  mysql_data:
